# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:
    encoders:
        Sipie\ProBundle\Entity\Usuario:
            algorithm: bcrypt

    providers:
        MySql:
            entity:
                class: SipieProBundle:Usuario
                property: rut
                # if you're using multiple entity managers
                # manager_name: customer


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/
            anonymous: ~
            provider: MySql
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /paciente
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
            security: true
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: ROLE_USER }