login_login:
    resource: "@LoginLoginBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
login_login_homepage:
    pattern: /index
    defaults: { _controller: LoginLoginBundle:Default:index}
    
login_login_login:
    pattern: /login
    defaults: { _controller: LoginLoginBundle:Default:login}
    
login_login_addp:
    pattern: /addp
    defaults: { _controller: LoginLoginBundle:Default:addp}