ficha:
    path:     /
    defaults: { _controller: "SipieProBundle:Ficha:index" }

ficha_show:
    path:     /{id}/show
    defaults: { _controller: "SipieProBundle:Ficha:show" }

ficha_new:
    path:     /new
    defaults: { _controller: "SipieProBundle:Ficha:new" }

ficha_create:
    path:     /create
    defaults: { _controller: "SipieProBundle:Ficha:create" }
    methods:  POST

ficha_edit:
    path:     /{id}/edit
    defaults: { _controller: "SipieProBundle:Ficha:edit" }

ficha_update:
    path:     /{id}/update
    defaults: { _controller: "SipieProBundle:Ficha:update" }
    methods:  [POST, PUT]

ficha_delete:
    path:     /{id}/delete
    defaults: { _controller: "SipieProBundle:Ficha:delete" }
    methods:  [POST, DELETE]
